// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmHCkFfFx4YfTBgd_VEfzWc1yg2dYFdyM',
    appId: '1:941761206155:web:db7dbc3a2bf35ccfb0018e',
    messagingSenderId: '941761206155',
    projectId: 'whatsapp-815f9',
    authDomain: 'whatsapp-815f9.firebaseapp.com',
    storageBucket: 'whatsapp-815f9.appspot.com',
    measurementId: 'G-6VW35VZK0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4sFGoJsyDtQLaF6YLX0w-8qI_tLDHuk4',
    appId: '1:941761206155:android:922ec54386a49a1eb0018e',
    messagingSenderId: '941761206155',
    projectId: 'whatsapp-815f9',
    storageBucket: 'whatsapp-815f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACCzlXqtbSUS2jYWvXuPPjRqhp-vdn-Mc',
    appId: '1:941761206155:ios:9e5e0d8c0aa3ea0ab0018e',
    messagingSenderId: '941761206155',
    projectId: 'whatsapp-815f9',
    storageBucket: 'whatsapp-815f9.appspot.com',
    iosBundleId: 'com.jesseld.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACCzlXqtbSUS2jYWvXuPPjRqhp-vdn-Mc',
    appId: '1:941761206155:ios:9e5e0d8c0aa3ea0ab0018e',
    messagingSenderId: '941761206155',
    projectId: 'whatsapp-815f9',
    storageBucket: 'whatsapp-815f9.appspot.com',
    iosBundleId: 'com.jesseld.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmHCkFfFx4YfTBgd_VEfzWc1yg2dYFdyM',
    appId: '1:941761206155:web:72540d3c14b34709b0018e',
    messagingSenderId: '941761206155',
    projectId: 'whatsapp-815f9',
    authDomain: 'whatsapp-815f9.firebaseapp.com',
    storageBucket: 'whatsapp-815f9.appspot.com',
    measurementId: 'G-TQDXM2WHB1',
  );
}
